name: NS2d
file: evaluate.py

model: MoEPOT
dataset: ns2d
use_writer: False
res: 128
modes: 20
width: 32
lr: 0.001
lr_method: cycle
warmup_epochs: 40
step_size: 100
step_gamma: 0.5
epochs: 200
noise_scale: 0.0005
T_ar: 1
use_ln: 1
normalize: 0
T_bundle: 1
grad_clip: 10000.0
n_channels: 4
n_class: 6

test_paths: [
  'ns2d_fno_1e-5',
  'ns2d_fno_1e-3',
  'ns2d_pdb_M1e-1_eta1e-2_zeta1e-2',
  'swe_pdb',
  'dr_pdb',
  'cfdbench'
]

#####################################################
##########   Model-Ti
#####################################################
resume_path: 'logs_pretrain/checkpoints/model_moepot_tiny.pth'
tasks:
 comment: ['t-eva']
 batch_size: [20]
 mlp_ratio: [1]
 res: [128]
 modes: [32]
 patch_size: [8]
 width: [512]
 n_layers: [4]
 n_blocks: [4]

######################################################
###########   DPOT-S
######################################################
#resume_path: './logs_pretrain/checkpoints/model_moepot_small.pth'
#tasks:
#  comment: ['s-eva']
#  batch_size: [20]
#  mlp_ratio: [1]
#  res: [128]
#  modes: [32]
#  patch_size: [8]
#  width: [1024]
#  n_layers: [6]
#  n_blocks: [8]

#####################################################
##########   DPOT-M
#####################################################
#resume_path: './logs_pretrain/checkpoints/model_moepot_medium.pth'
#tasks:
#  comment: ['m-eva']
#  batch_size: [20]
#  mlp_ratio: [2]
#  res: [128]
#  modes: [32]
#  patch_size: [8]
#  width: [1024]
#  n_layers: [8]
#  n_blocks: [8]

